spring:
  application:
    name: "configserver"
  profiles:
    active: git # where do we pull the profile
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/snckl/springboot-config" # repo uri
          default-label: main # branch name
          timeout: 5 # Waits for 5 seconds to connect then throws exception
          clone-on-start: true # clone the GitHub repo to local system
          force-pull: true # overwrite all local changes

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "QnRh6ygIXz4IFcxN7ICqy0HrNgID2MJb" # Key for encryption

server:
  port: 8071